# Default initial positions for ecosense_arm's ros2_control fake system

initial_positions:
  Elbow: 1.51
  Gripper: 0
  Shoulder_Pitch: -1.6836
  Shoulder_Rotation: 0.0
  Wrist_Pitch: -0.3645
  Wrist_Roll: 0