/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.40.0
 * Product:       sht4x
 * Model-Version: 2.1.1
 */
/*
 * Copyright (const stmdev_ctx_t *ctx, c) 2024, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (const stmdev_ctx_t *ctx, INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (const stmdev_ctx_t *ctx, INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef SENSIRIONI2CSHT4X_H
#define SENSIRIONI2CSHT4X_H

//#include <SensirionCore.h>
//#include <Wire.h>
#include <stdint.h>

#define SHT40_I2C_ADDR_44 0x44
//#define SHT40_I2C_ADDR_45 0x45
//#define SHT41_I2C_ADDR_44 0x44
//#define SHT41_I2C_ADDR_45 0x45
//#define SHT45_I2C_ADDR_44 0x44
//#define SHT45_I2C_ADDR_45 0x45

#define	SHT4X_MEASURE_HIGH_PRECISION_RAW_CMD_ID 				0xfd
#define	SHT4X_MEASURE_MEDIUM_PRECISION_RAW_CMD_ID 			0xf6
#define	SHT4X_MEASURE_LOWEST_PRECISION_RAW_CMD_ID 			0xe0
#define	SHT4X_ACTIVATE_HIGHEST_HEATER_POWER_LONG_RAW_CMD_ID 	0x39
#define	SHT4X_ACTIVATE_HIGHEST_HEATER_POWER_SHORT_RAW_CMD_ID 	0x32
#define	SHT4X_ACTIVATE_MEDIUM_HEATER_POWER_LONG_RAW_CMD_ID	0x2f
#define	SHT4X_ACTIVATE_MEDIUM_HEATER_POWER_SHORT_RAW_CMD_ID 	0x24
#define	SHT4X_ACTIVATE_LOWEST_HEATER_POWER_LONG_RAW_CMD_ID 	0x1e
#define	SHT4X_ACTIVATE_LOWEST_HEATER_POWER_SHORT_RAW_CMD_ID 	0x15
#define	SHT4X_SERIAL_NUMBER_CMD_ID 								0x89
#define	SHT4X_SOFT_RESET_CMD_ID 								0x94

/* Structure pour interface avec l'I2C */
typedef int32_t (*stmdev_write_ptr)(void *, const uint8_t *, uint16_t);
typedef int32_t (*stmdev_read_ptr)(void *, uint8_t *, uint16_t);
typedef void (*stmdev_mdelay_ptr)(uint32_t);

typedef struct {
	stmdev_write_ptr write_i2c;
	stmdev_read_ptr read_i2c;
	stmdev_mdelay_ptr mdelay;
	void *handle;
	uint8_t i2cAddress;
} stmdev_ctx_t;

/**
 * @brief softReset
 *
 * Perform a soft reset.
 *
 * @note A reset of the sensor can be achieved in three ways: • Soft reset:
 * use this function • I2C general call: all devices on the I2C bus are
 * reset by sending the command 0x06 to the I2C address 0x00. • Power down
 * (const stmdev_ctx_t *ctx, incl.pulling SCL and SDA low)
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_softReset(const stmdev_ctx_t *ctx);

/**
 * @brief Run measurement with high precision
 *
 * SHT4x command for a single shot measurement with high repeatability.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_measureHighPrecision(const stmdev_ctx_t *ctx, float *aTemperature, float *aHumidity);

/**
 * @brief Run measurement with medium precision
 *
 * SHT4x command for a single shot measurement with medium repeatability.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_measureMediumPrecision(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity);

/**
 * @brief Run measurement with low precision
 *
 * SHT4x command for a single shot measurement with low repeatability.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_measureLowestPrecision(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity);

/**
 * @brief Run measurement with high precision and the highest power heater
 * for 1s
 *
 * SHT4x command to activate highest heater power and perform a single shot
 * high precision measurement for 1s.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateHighestHeaterPowerLong(const stmdev_ctx_t *ctx, float* aTemperature,
		float* aHumidity);

/**
 * @brief Run measurement with high precision and the highest power heater
 * for 0.1s
 *
 * SHT4x command to activate highest heater power and perform a single shot
 * high precision measurement for 0.1s.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateHighestHeaterPowerShort(const stmdev_ctx_t *ctx, float* aTemperature,
		float* aHumidity);

/**
 * @brief Run measurement with high precision and the medium power heater
 * for 1s
 *
 * SHT4x command to activate medium heater power and perform a single shot
 * high precision measurement for 1s.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateMediumHeaterPowerLong(const stmdev_ctx_t *ctx, float* aTemperature,
		float* aHumidity);

/**
 * @brief Run measurement with high precision and the medium power heater
 * for 0.1s
 *
 * SHT4x command to activate medium heater power and perform a single shot
 * high precision measurement for 0.1s.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateMediumHeaterPowerShort(const stmdev_ctx_t *ctx, float* aTemperature,
		float* aHumidity);

/**
 * @brief Run measurement with high precision and the lowest power heater
 * for 1s
 *
 * SHT4x command to activate lowest heater power and perform a single shot
 * high precision measurement for 1s.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateLowestHeaterPowerLong(const stmdev_ctx_t *ctx, float* aTemperature,
		float* aHumidity);

/**
 * @brief Run measurement with high precision and the lowest power heater
 * for 0.1s
 *
 * SHT4x command to activate lowest heater power and perform a single shot
 * high precision measurement for 0.1s.
 *
 * @param[out] aTemperature Converted from Raw to degrees celsius by (const stmdev_ctx_t *ctx, 175
 * * Raw_value / 65535) - 45
 * @param[out] aHumidity Converted from Raw to percent relative humdity by
 * (const stmdev_ctx_t *ctx, 125 * Raw_value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateLowestHeaterPowerShort(const stmdev_ctx_t *ctx, float* aTemperature,
		float* aHumidity);

/**
 * @brief measureHighPrecisionRaw
 *
 * SHT4x command for a single shot measurement with high repeatability.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_measureHighPrecisionRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief measureMediumPrecisionRaw
 *
 * SHT4x command for a single shot measurement with medium repeatability.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_measureMediumPrecisionRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief measureLowestPrecisionRaw
 *
 * SHT4x command for a single shot measurement with lowest repeatability.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_measureLowestPrecisionRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief activateHighestHeaterPowerLongRaw
 *
 * SHT4x command to activate highest heater power and perform a single shot
 * high precision measurement for 1s.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateHighestHeaterPowerLongRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief activateHighestHeaterPowerShortRaw
 *
 * SHT4x command to activate highest heater power and perform a single shot
 * high precision measurement for 0.1s.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateHighestHeaterPowerShortRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief activateMediumHeaterPowerLongRaw
 *
 * SHT4x command to activate medium heater power and perform a single shot
 * high precision measurement for 1s.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateMediumHeaterPowerLongRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief activateMediumHeaterPowerShortRaw
 *
 * SHT4x command to activate medium heater power and perform a single shot
 * high precision measurement for 0.1s.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateMediumHeaterPowerShortRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief activateLowestHeaterPowerLongRaw
 *
 * SHT4x command to activate lowest heater power and perform a single shot
 * high precision measurement for 1s.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateLowestHeaterPowerLongRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief activateLowestHeaterPowerShortRaw
 *
 * SHT4x command to activate lowest heater power and perform a single shot
 * high precision measurement for 0.1s.
 *
 * @param[out] temperatureRaw Temperature Raw. Convert to degrees
 * celsius by (const stmdev_ctx_t *ctx, 175 * value / 65535) - 45
 * @param[out] humidityRaw Humidity Raw. Convert to degrees celsius by
 * (const stmdev_ctx_t *ctx, 125
 * * value / 65535) - 6
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_activateLowestHeaterPowerShortRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw,
		uint16_t* humidityRaw);

/**
 * @brief serialNumber
 *
 * Read out the serial number
 *
 * @param[out] serialNumber Unique serial number
 *
 * @note Each sensor has a unique serial number that is assigned by
 * Sensirion during production.It is stored in the one-time-programmable
 * memory and cannot be manipulated after production.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int32_t sht4x_serialNumber(const stmdev_ctx_t *ctx, uint32_t* serialNumber);

/**
 * @brief sht4x_serialNumber
 *
 * @param[in] temperatureRaw
 *
 * @return Converted from raw to degrees celsius by (const stmdev_ctx_t *ctx, 175 * Raw_value /
 * 65535) - 45
 */
float sht4x_convertRawTemperature(uint16_t temperatureRaw);

/**
 * @brief sht4x_convertRawTemperature
 *
 * @param[in] humidityRaw
 *
 * @return Converted from raw to percent relative humdity by (const stmdev_ctx_t *ctx, 125 *
 * Raw_value / 65535) - 6
 */
float sht4x_convertRawHumidity(uint16_t humidityRaw);

#endif  // SENSIRIONI2CSHT4X_H
