/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.40.0
 * Product:       sht4x
 * Model-Version: 2.1.1
 */
/*
 * Copyright (c) 2024, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "Sensors/sht40/sensirion_sht4x.h"

//#include <Arduino.h>

// make sure that we use the proper definition of NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

uint8_t _i2cAddress;

float sht4x_convertRawTemperature(uint16_t temperatureRaw) {
	float temperature = 0.0;
	temperature = (float)(temperatureRaw);
	temperature = ((temperature * 175.0) / 65535.0) - 45.0;
	return temperature;
}

float sht4x_convertRawHumidity(uint16_t humidityRaw) {
	float humidity = 0.0;
	humidity = (float)(humidityRaw);
	humidity = ((humidity * 125.0) / 65535.0) - 6.0;
	return humidity;
}

static void sht4x_getVal1andVal2(const uint8_t *buffer, uint16_t *val1, uint16_t *val2) {
	*val1 = ((uint16_t)buffer[0]<<8) | (uint16_t)buffer[1];
	*val2 =	((uint16_t)buffer[3]<<8) | (uint16_t)buffer[4];
}

int32_t sht4x_measureHighPrecision(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int32_t localError = 0;
	localError = sht4x_measureHighPrecisionRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_measureMediumPrecision(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int32_t localError = 0;
	localError = sht4x_measureMediumPrecisionRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_measureLowestPrecision(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int32_t localError = 0;
	localError = sht4x_measureLowestPrecisionRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_activateHighestHeaterPowerLong(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int32_t localError = 0;
	localError = sht4x_activateHighestHeaterPowerLongRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_activateHighestHeaterPowerShort(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int32_t localError = 0;
	localError = sht4x_activateHighestHeaterPowerShortRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_activateMediumHeaterPowerLong(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int32_t localError = 0;
	localError = sht4x_activateMediumHeaterPowerLongRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_activateMediumHeaterPowerShort(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int16_t localError = 0;
	localError = sht4x_activateMediumHeaterPowerShortRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_activateLowestHeaterPowerLong(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int16_t localError = 0;
	localError = sht4x_activateLowestHeaterPowerLongRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_activateLowestHeaterPowerShort(const stmdev_ctx_t *ctx, float* aTemperature, float* aHumidity) {
	uint16_t tempRaw = 0;
	uint16_t humiRaw = 0;
	int32_t localError = 0;
	localError = sht4x_activateLowestHeaterPowerShortRaw(ctx, &tempRaw, &humiRaw);
	if (localError != NO_ERROR) {
		return localError;
	}

	*aTemperature = sht4x_convertRawTemperature(tempRaw);
	*aHumidity = sht4x_convertRawHumidity(humiRaw);
	return localError;
}

int32_t sht4x_measureHighPrecisionRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_MEASURE_HIGH_PRECISION_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(10); //attente de la fin de la conversion (pourquoi 2ms ???)

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // recuperation de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_measureMediumPrecisionRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_MEASURE_MEDIUM_PRECISION_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(10); //attente de la fin de la conversion (pourquoi 2ms ???)

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_measureLowestPrecisionRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_MEASURE_LOWEST_PRECISION_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(10); //attente de la fin de la conversion (pourquoi 2ms ???)

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_activateHighestHeaterPowerLongRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_ACTIVATE_HIGHEST_HEATER_POWER_LONG_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(1010); //attente de la fin du chauffage (1s) + conversion

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_activateHighestHeaterPowerShortRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_ACTIVATE_HIGHEST_HEATER_POWER_SHORT_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(110); //attente de la fin du chauffage (100ms)+ conversion

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_activateMediumHeaterPowerLongRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_ACTIVATE_MEDIUM_HEATER_POWER_LONG_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(1010); //attente de la fin du chauffage (1s) + conversion

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_activateMediumHeaterPowerShortRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_ACTIVATE_MEDIUM_HEATER_POWER_SHORT_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(110); //attente de la fin du chauffage (100ms)+ conversion

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_activateLowestHeaterPowerLongRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_ACTIVATE_LOWEST_HEATER_POWER_LONG_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(1010); //attente de la fin du chauffage (1s) + conversion

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_activateLowestHeaterPowerShortRaw(const stmdev_ctx_t *ctx, uint16_t* temperatureRaw, uint16_t* humidityRaw) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];

	write_buffer[0] = SHT4X_ACTIVATE_LOWEST_HEATER_POWER_SHORT_RAW_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(110); //attente de la fin du chauffage (100ms)+ conversion

		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération de la temperature et de l'humidité

		if (!localError)
			sht4x_getVal1andVal2(read_buffer, temperatureRaw, humidityRaw);
	}

	return localError;
}

int32_t sht4x_serialNumber(const stmdev_ctx_t *ctx, uint32_t* serialNumber) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1], read_buffer[6];
	uint16_t val1, val2;

	write_buffer[0] = SHT4X_SERIAL_NUMBER_CMD_ID;
	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande

	if (!localError) {
		ctx->mdelay(10);

		// pas de contrôle du status, se termine par NACK
		localError = ctx->read_i2c(ctx->handle, read_buffer, 6); // Récupération du serial number

		if (!localError) {
			sht4x_getVal1andVal2(read_buffer, &val1, &val2);
			*serialNumber = ((uint32_t)val1<<16) | (uint32_t)val2;
		}
	}

	return localError;
}

int32_t sht4x_softReset(const stmdev_ctx_t *ctx) {
	int32_t localError = NO_ERROR;
	uint8_t write_buffer[1];

	write_buffer[0] = SHT4X_SOFT_RESET_CMD_ID;

	localError = ctx->write_i2c(ctx->handle, write_buffer, 1); // Envoi de la commande
	if (!localError) ctx->mdelay(10);

	return localError;
}

